// Code generated by goctl. DO NOT EDIT.
// Source: user-rpc.proto

package userservice

import (
	"context"

	"goservertemplate/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginResponse = user.LoginResponse
	User          = user.User

	UserService interface {
		Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}
