// Code generated by goctl. DO NOT EDIT.
package types

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Loginres struct {
	Token string `json:"token"`
}

type Info struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
